language: node_js
node_js:
- "16"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - npm install @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/portfolio
  on: